### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by FelixINX** [octobercms/install#70]
Hi,

A multilanguage installer would be very nice!

**Comment by awaysoft** [comment]
+1

**Comment by awaysoft** [comment]
Now I'm doing this.

**Comment by awaysoft** [comment]
@felixinx I have done it, you can test it in my fork, when I finished zh-cn lang file, I'll pull request to this.

**Comment by awaysoft** [comment]
@felixinx Done it,welcome to test.

**Comment by felixinx** [comment]
Awesome. I will work on a french version of the installer.

**Comment by awaysoft** [comment]
@felixinx I don't know, I just make a very simple lang system, you know, Chinese can be shown in UTF-8, so you can have a try to replace title?

**Comment by felixinx** [comment]
I don't know why, but my file isn't working. Here is a snippet of the file. https://gist.github.com/felixinx/9f2ebc28147ffacc1a91

Also, there are some things that may be done before posting the PR (or before merge);

- [ ] Make a multilanguage website of the OctoberCMS
- [ ] Contributing file

**Comment by awaysoft** [comment]
@felixinx I see, in line 53,"d\'installation" must change to "d\\\'dinstallation", the same to line 54/55, because this string need to show in html, single ' may cause javascript error.

Sorry for other things, I'm not a core member of OctoberCMS, I just make some contribute in chinese language, maybe in future, I will do more contribute.

Maybe @daftspunk can do these.

**Comment by daftspunk** [comment]
If this is still an issue, please log it in the main October repo.

**Comment by daftspunk** [comment]
Installer in v2.0 has ML support
